### DISCUSSION TITLE
이미지의 비율을 유지하는 방법을 소개해주세요

### DISCUSSION THREAD

**Discussion by javascriptbiggosoo** [wanted-9th-3team/frontend-study#79] [프론트 기술 질문 공간]
이미지가 초기 비율과 달라지는 변형을 원하지 않는 경우 어떻게 해야할까요

**Comment by michoball** [comment]
기본적으로 img의 width와 height를 지정해주면 해당 크기에 맞게 이미지가 만들어집니다. 

 css 요소중
` aspect-ratio: auto || <ratio>` 를 상용하거나 

`object-fit: ` 을 사용해 img의 비율을 유지할 수도 있습니다.

**Comment by WooGie911** [comment]
css 에서 img 태그의  cover 속성을 사용하면 이미지의 초기 비율을 지킬수 있습니다.

이미지를 배경이미지로 넣을 경우엔 background-size: cover 를,
img 태그의 이미지의 비율을 설정할 땐 object-fit: cover 를 사용하면 됩니다.

**Comment by javascriptbiggosoo** [comment]
max-width, max-height, auto 방식만 사용하다 최근에 object-fit을 알게 됐습니다.
    
```css
img {
  display: block;
  max-width:230px;
  max-height:95px;
  width: auto;
  height: auto;
}
```
    
```html
<p>This image is originally 400x400 pixels, but should get resized by the CSS:</p>
<img width="400" height="400" src="http://i.stack.imgur.com/aEEkn.png">
```
    
이것보다 object-fit이 간편한 것 같습니다. https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit
