### DISCUSSION TITLE
사용해본 CSS 관련 라이브러리

### DISCUSSION THREAD

**Discussion by WooGie911** [wanted-9th-3team/frontend-study#98] [프론트 기술 질문 공간]
사용해본 CSS 라이브러리 중 기억에 남는 것이 있나요?
이유는 무엇인가요? 장단점에 대해 설명해주세요.

**Comment by michoball** [comment]
css 관련 라이브러리 하며는 당연 styled-components를 말할 수 있을 것 같습니다. 
css - in - js 방식으로 js 파일안에 css  styling을 구현할 수 있게 해주는 라이브러리입니다. 
기존 html 태그를 특정 스타일을 씌운 새로운 이름으로 사용이가능하고 또 이를 확장해서 다른 이름으로 다른 컴포넌트에서 사용할 수 도 있습니다. 

그리고 제일 큰 장점 중 하나는 style 안에 props 를 받을 수 있어서 props 에 따른 다른 스타일을 입힐 수도 있다는 것입니다. 

단점은 css 보다 느리고 외부 의존성을 늘리게 된다는 점과 러닝커브가 있을 것 같습니다. 

이외에도 어떤 적정 범위내에서 컴포넌트에 styled-components를 입힐지가 모호한 경우도 발생한다는 점과 nextjs 에서 사용하기 위해서 추가적인 작업이 들어가고 꼭 csr 에서 사용해야한다는 점이 있겠습니다.

**Comment by javascriptbiggosoo** [comment]
Styled Components는 React에서 CSS-in-JS 라이브러리 중 하나로, 컴포넌트 스타일링의 유연성과 재사용성을 높이는데 매우 유용합니다.

Styled Components의 주요 장점은 다음과 같습니다:

- **컴포넌트 범위의 스타일**: 각 스타일드 컴포넌트는 독립적으로 스타일이 적용되므로, 클래스 이름 충돌을 걱정할 필요가 없습니다.
이것은 코드의 명확성과 유지보수성을 향상시킵니다.
- **동적 스타일링**: props를 통해 스타일을 쉽게 변경할 수 있습니다.
이것은 컴포넌트 기반의 설계와 잘 어울립니다.
- **재사용성**: 스타일드 컴포넌트를 만들면, 이를 다른 컴포넌트에서 재사용할 수 있습니다.
- **테마 지원**: Styled Components는 테마를 제공하여 애플리케이션 전체의 스타일을 쉽게 일관성 있게 유지할 수 있습니다.

```jsx
import styled from 'styled-components';

// 스타일드 컴포넌트 생성
const Button = styled.button`
  background: ${props => props.primary ? 'palevioletred' : 'white'};
  color: ${props => props.primary ? 'white' : 'palevioletred'};
  font-size: 1em;
  margin: 1em;
  padding: 0.25em 1em;
  border: 2px solid palevioletred;
  border-radius: 3px;
`;

// 컴포넌트 사용
function App() {
  return (
    <div>
      <Button primary>Primary Button</Button>
      <Button>Secondary Button</Button>
    </div>
  );
}

export default App;

```

이 예시에서는 `Button`이라는 스타일드 컴포넌트를 만들었습니다.
이 컴포넌트는 `primary`라는 prop을 받아서 버튼의 배경색과 글자색을 바꿀 수 있습니다.
이렇게 Styled Components를 사용하면 CSS를 JavaScript 내에서 직접 작성하고, 컴포넌트의 props에 따라 동적으로 스타일을 변경할 수 있습니다.
+ styled component에 적절한 작명을 함으로써 직관성을 높일 수도 있겠지요.

Styled Components를 사용하지 않고 CSS 또는 CSS 모듈을 사용해 위의 예제를 구현하려면 아래와 같이 작성할 수 있습니다:

```jsx
import React from 'react';
import './App.css';

function App() {
  return (
    <div>
      <button className="primary-button">Primary Button</button>
      <button className="secondary-button">Secondary Button</button>
    </div>
  );
}

export default App;

```

`App.css` 

```css
.primary-button {
  background: palevioletred;
  color: white;
  font-size: 1em;
  margin: 1em;
  padding: 0.25em 1em;
  border: 2px solid palevioletred;
  border-radius: 3px;
}

.secondary-button {
  background: white;
  color: palevioletred;
  font-size: 1em;
  margin: 1em;
  padding: 0.25em 1em;
  border: 2px solid palevioletred;
  border-radius: 3px;
}

```

하지만 이러한 접근법에는 몇 가지 잠재적인 문제가 있습니다:

- **스타일 충돌**: CSS는 전역적인 네임스페이스를 가지므로, 동일한 클래스 이름을 사용하면 스타일이 충돌할 수 있습니다.
Styled Components를 사용하면 각 컴포넌트는 독립적인 스타일을 가집니다.
- **재사용성과 유지보수성의 문제**: CSS 클래스를 직접 관리하면 동일한 스타일을 다른 컴포넌트에서 재사용하기가 더 어렵습니다.
또한 스타일 변경이 필요할 때 CSS 파일과 JavaScript 파일을 모두 수정해야 할 수 있습니다.
- **동적 스타일링의 어려움**: JavaScript 파일과 CSS 파일이 분리되어 있기 때문에, 동적으로 스타일을 변경하기 어렵습니다.
예를 들어, 버튼의 색상을 prop에 따라 변경하려면 추가적인 로직이 필요합니다.

이러한 문제점들 때문에, 많은 개발자들이 CSS-in-JS 라이브러리인 Styled Components와 같은 도구를 사용하여 스타일링 문제를 해결하려고 합니다.
